### ISSUE TITLE
Process completed with exit code 1

### ISSUE THREAD

**Issue by jaredsam** [wdzeng/shopee-coins-bot#16]
第一次手動簽到就失敗了，
code 1 也不在作者寫的錯誤碼中，
請問這怎解決？

**Comment by jaredsam** [comment]
沒有收到簡訊

**Comment by wdzeng** [comment]
了解，我知道 bug 在哪裡了，一小時內修好！

**Comment by wdzeng** [comment]
Hi @jaredsam,

你遇到的錯誤源自兩件事情，一是蝦皮寄出的簡訊你沒有收到，二是機器人沒有處理好驗證逾時的情況。關於第一點我無能為力，但第二點我已經修復並發布新版機器人。請你再試試看。

Thanks!

**Comment by wdzeng** [comment]
@jaredsam:

你重跑的那個是排成的簽到，因為你沒有手動簽到成功過，你重跑排成簽到是沒有意義的。

請你再跑一次手動簽到才對。

Thanks!

**Comment by jaredsam** [comment]
後來手動排成簽到
Process completed with exit code 4.
沒收到簡訊 是無解了?

**Comment by wdzeng** [comment]
> 後來手動排成簽到
> Process completed with exit code 4.
> 沒收到簡訊 是無解了?

簡訊有寄出去。如果你沒收到的話也沒辦法ㄌ。
