### ISSUE TITLE
Failed to load cookies: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by yeuking** [wdzeng/shopee-coins-bot#17]
```
docker run -it -v ~/cookie/coin:/cookie hyperbola/shopee-coins-bot:1 -u 'username' -p 'password' -c /cookie
Start shopee coins bot v1.0.17.
Passing password from command line is considered insecure. Should use environment variable or password file.
Start to load cookies.
Failed to load cookies: EISDIR: illegal operation on a directory, read
Start to login shopee.
Try to login by username and password.
Login form submitted. Waiting for redirect.
Login failed: wrong password.
```

已经确定密码无误，但还是不让进。

**Comment by paul159321** [comment]
> ```
> docker run -it -v ~/cookie/coin:/cookie hyperbola/shopee-coins-bot:1 -u 'username' -p 'password' -c /cookie
> Start shopee coins bot v1.0.17.
> Passing password from command line is considered insecure. Should use environment variable or password file.
> Start to load cookies.
> Failed to load cookies: EISDIR: illegal operation on a directory, read
> Start to login shopee.
> Try to login by username and password.
> Login form submitted. Waiting for redirect.
> Login failed: wrong password.
> ```
> 
> 已经确定密码无误，但还是不让进。

先把cookie的檔案建立好
/cookie/coin  <-- 在cookie資料夾下建立coin這個 "檔案"
就正常了

**Comment by yeuking** [comment]
谢谢，我会先建立文档然后再做尝试。
