### ISSUE TITLE
docker 在 Windows 上無法設定 cookie 位置

### ISSUE THREAD

**Issue by LostSunset** [wdzeng/shopee-coins-bot#21]
您好，windows 系統下我以系統管理員權限之 cmd 輸入

```
docker run -it -v //c/cookie hyperbola/shopee-coins-bot:1 -u xxxxxx -p xxxxxxx -c /cookie
```

會出現以下訊息。

```
Passing password from command line is considered insecure. Should use environment variable or password file.
Start to load cookies.
Failed to load cookies: ENOENT: no such file or directory, open '/cookie'
Start to login shopee.
Try to login by username and password.
Login form submitted. Waiting for redirect.
Login failed: please login via SMS.
An SMS message is sent to your mobile. Once you click the link I will keep going. I will wait for you and please complete it in 10 minutes.
Login permitted.
Start to save cookie.
Failed to save cookie: EACCES: permission denied, open '/cookie'
Coin already received.
```

請問是否是 cookie 位置問題，不過我記得 `-v` 會自動創建
或是要先新增cookie檔，如果是要先新增 cookie 檔，請問該如何新增呢？

PS：感謝大大的開發，期待此 docker 有人發圖文教學，謝謝！

**Comment by wdzeng** [comment]
Hi,

我沒有在 Windows 上操作過 Docker，所以關於 mount file system 這件事可能沒辦法給你可靠的答覆。

我不確定在 Windows 上 `-v //c/cookie` 的意思是什麼。不過，對於 mount 機器上的 A 檔案到容器內 的 B 檔案這件事，有個前提是 A 檔案必須已經存在。如果不存在，mount 就不會成功，於是即使機器人把 cookie 存進 B 檔案內，也沒有任何意義。

要克服以上的問題，比較好的方法是 mount 資料夾。例如你想把 cookie 存在 C:\Users\myusername\shopee-cookie，你可能可以這樣下指令：

```
docker run -it -v "//c/Users/myusername:/secret" hyperbola/shopee-coins-bot:1 -c /secret/shopee-cookie -u xxx -p xxx
```

如果出現沒有權限的錯誤訊息，可以試試看 docker 的 `-u` 參數。

**Comment by wdzeng** [comment]
> 如果不存在，mount 就不會成功

更正說法。如果 A 檔案不存在，docker 會在宿主機建立名為 A 的資料夾。

由於 cookie 必須是檔案，因此會造成機器人儲存 cookie 失敗。

**Comment by rs980330603** [comment]
非常感謝!
問題已解決，由於我在windows有安裝wsl2子系統，沒注意是 docker 是在Ubuntu 22.0.4下執行，
解決方式如下:
勾選wsl2
![image](https://user-images.githubusercontent.com/108474187/177164452-0621bb74-dc51-4db0-9f7f-52e1b62e63cb.png)
看是安裝哪一個版本或是希望docker在哪個ubuntu版本環境下執行就開啟
![image](https://user-images.githubusercontent.com/108474187/177164799-5d78a667-e48b-406b-ba75-e73acaa08162.png)
最後在ubuntu shell (windows的視窗) 下輸入(myusername需要改成你現在的windows使用者名稱以及1001在下面解釋):
docker run -u 1001 -it -v "/mnt/c/Users/myusername:/secret" hyperbola/shopee-coins-bot:1 -c /secret/shopee-cookie  -u xxx -p xxx
![image](https://user-images.githubusercontent.com/108474187/177165408-80041654-38f2-4356-bc3b-6bcec2d4cb77.png)
1001怎麼來的可以參考:
id -u
id -g
![image](https://user-images.githubusercontent.com/108474187/177165701-40d80466-4031-4b54-8d73-353858f3fdcd.png)

**Comment by LostSunset** [comment]
非常感謝兩位，問題解決 !
也好奇rs980330603大的最後問題。

**Comment by wdzeng** [comment]
> 不好意思，想再問一個問題，請問如果要達成每日簽到的條件，
> 是否電腦需一直開著且 docker 不能 stop？

是的。這不是一般人能負擔的。

**Comment by wdzeng** [comment]
> 想請教為什麼必須以 root 的身分執行才會成功呢？
> 如果以其他使用者執行就會顯示檔案不存在...
> 
> ![螢幕擷取畫面 2022-07-06 201731](https://user-images.githubusercontent.com/43649946/177548258-f835325c-e97b-432c-a984-1b8addf27cff.png)
> 

Hi,

請盡量以複製貼上程式碼取代截圖。

這份專案終究是以熟悉 docker 的使用者為目標，因此有使用上不符合預期的情況時，可以先試著在網路上尋找與 docker 相關的問題與解答。

你遇到的狀況可以 `--user` 解決。

**Comment by Johnwang860424** [comment]
> 
> Hi,
> 
> 請盡量以複製貼上指令代替螢幕截圖，因為截圖是很不容易閱讀的。
> 
> 關於你遇到的問題，我猜跟你下的 `-v` 參數有關。但因為你圖上馬賽克看不太清楚你怎麼下，我沒辦法給你肯定的回覆。
> 
> 這份專案終究是以熟悉 docker 的使用者為目標，因此有使用上不符合預期的情況時，可以先試著在網路上尋找與 docker 相關的問題與解答。

抱歉，以後會多加注意的。
跟您猜的一樣是與 `-v`參數有關，改成以下指令就可以順利運行了，謝謝。
```
sudo docker run -u 1000 -it -v "/mnt/c/Users/John Wang:/secret" hyperbola/shopee-coins-bot:1 -c /secret/cookie  -u account -p password
```

**Comment by always9650ISU** [comment]
windows 指令範例
path = C:\Users\Yu

docker run  -it -v //c/Users/Yu:/secret hyperbola/shopee-coins-bot:1 -c /secret/cookie -u xxx -p xxx
docker run -it -v //c/Users/Yu:/secret hyperbola/shopee-coins-bot:1 -c /secret/cookie
