### ISSUE TITLE
cookie檔案問題

### ISSUE THREAD

**Issue by TWjohnwang** [wdzeng/shopee-coins-bot#22]
抱歉，想請教一下，我有用帳號密碼並透過簡訊認證登入成功，但想嘗試以cookie登入時卻都無法成功。
想請教您說需儲存cookie的位置，但我在執行以下兩行時，卻噴錯了，請問是否有更詳細的教學呢

docker run -it -v /path/to/somewhere:/cookie \
    hyperbola/shopee-coins-bot:1 -u username -p password -c /cookie

**Comment by LostSunset** [comment]
幫w作者回答，可以參考我這邊的issue
https://github.com/wdzeng/shopee-coins-bot/issues/21

**Comment by TWjohnwang** [comment]
> 

抱歉，發了以後才發現已經有別人問過同樣的issue了...謝謝作者分享。
