### ISSUE TITLE
Failed to load cookies: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by a31550277** [wdzeng/shopee-coins-bot#23]
請問這是什麼問題？cookie 檔案要給什麼檔案格式？

**Comment by a31550277** [comment]
我是用群暉的DOCKER 所以是用設環境變數跟檔案連結的方式的
請問要如何設定？

**Comment by wdzeng** [comment]
Hi,

你要不要講一下你怎麼下參數的？

**Comment by a31550277** [comment]
我儲存空間掛了個cookie.txt到/cookie
![image](https://user-images.githubusercontent.com/88643487/178030993-82522587-073c-4a08-8014-ed54eabb5b40.png)
然後環境變數除了預設的PATH、CHROME_BIN、CHROME_PATH、TZ以外再加了PASSWORD、USERNAME、COOKIE
其中USERNAME跟PASSWORD是直接指定
COOKIE則是給/cookie
![image](https://user-images.githubusercontent.com/88643487/178030953-c98d64d0-9cfa-4eb9-af3e-c986621393e0.png)

**Comment by wdzeng** [comment]
你的截圖跟群暉的產品有關吧？抱歉，我沒用過群暉的東西，也不清楚那張圖的意義，大概幫不了你。

**Comment by ray1025** [comment]
@a31550277 我在synology上執行成功了。
![螢幕擷取畫面 (16)剪](https://user-images.githubusercontent.com/49980364/179159730-c86c373e-6c62-451f-9cd3-d4b9c3921349.png)

你先在Linux電腦(模擬的也可以)利用作者的教學執行一次帳號密碼登入，並自動完成一個cookie檔案。
把cookie檔案複製到NAS裡面，並且要給這個cookie檔案666權限。
然後到控制台---任務排程表---新增---排程任務---使用者定義指令碼，設定好排程和指令即可。

**Comment by a31550277** [comment]
我之前依照win10電腦那邊的方法給了
檔案系統：
    docker/蝦皮：/secret
跟環境變數
    COOKIE：/secret/shopee-cookie
他就生成檔案了
然後再手動指定檔案系統
    docker/蝦皮/shopee-cookie：cookie
![Screenshot_20220715-145116_Chrome](https://user-images.githubusercontent.com/88643487/179168121-406f0607-9a9a-4c73-b602-aeb231c67648.png)

並把環境變數改為
    COOKIE：cookie
![Screenshot_20220715-145119_Chrome](https://user-images.githubusercontent.com/88643487/179168168-d55ebdd0-d209-475b-9557-4ae16059a03f.png)

他就正常行動了

**Comment by a31550277** [comment]
然後我重開部分是排程一個
Docker restart shopee-bot指令(shopee-bot為我的容器名)

**Comment by ray1025** [comment]
@a31550277 你用這樣可以排程嗎?

**Comment by wdzeng** [comment]
> 我之前依照win10電腦那邊的方法給了
> 檔案系統：
>     docker/蝦皮：/secret
> 跟環境變數
>     COOKIE：/secret/shopee-cookie
> 他就生成檔案了
> 然後再手動指定檔案系統
>     docker/蝦皮/shopee-cookie：cookie
> ![Screenshot_20220715-145116_Chrome](https://user-images.githubusercontent.com/88643487/179168121-406f0607-9a9a-4c73-b602-aeb231c67648.png)
> 
> 並把環境變數改為
>     COOKIE：cookie
> ![Screenshot_20220715-145119_Chrome](https://user-images.githubusercontent.com/88643487/179168168-d55ebdd0-d209-475b-9557-4ae16059a03f.png)
> 
> 他就正常行動了

沒錯，這是正確的配置方式。

**Comment by ray1025** [comment]
OK，學習了。

**Comment by ray1025** [comment]
@a31550277 
您好，我在synology上執行遇到問題，專案每週都會卡在

Start shopee coins bot v1.1.0.
Start to load cookies.
Cookies loaded.
Start to login shopee.
Try to login by username and password.
Login form submitted. Waiting for redirect.
Operation timeout exceeded.

我已經試了兩週都要用電腦重新跑一次cookie再傳過去synology
請問你也會這樣嗎???
要如何解決???
謝謝。

**Comment by wdzeng** [comment]
> @a31550277 
> 您好，我在synology上執行遇到問題，專案每週都會卡在
> 
> Start shopee coins bot v1.1.0.
> Start to load cookies.
> Cookies loaded.
> Start to login shopee.
> Try to login by username and password.
> Login form submitted. Waiting for redirect.
> Operation timeout exceeded.
> 
> 我已經試了兩週都要用電腦重新跑一次cookie再傳過去synology
> 請問你也會這樣嗎???
> 要如何解決???
> 謝謝。

Hi, 請問是否有截圖？這可能是 bug。

**Comment by ray1025** [comment]
W大您好，我用synology的docker一直無法截圖出來，我再試試@@

**Comment by ray1025** [comment]
@wdzeng 
大神您好：
我在synology的docker上把cookie先移除，然後利用指令把截圖結出來了，是停在這邊。

輸出：
Start shopee coins bot v1.1.0.
No cookies given. Will try to login using username and password.
Start to login shopee.
Try to login by username and password.
Login form submitted. Waiting for redirect.
A screenshot has been put at /sc/screenshot.png.
Operation timeout exceeded.

截圖：
![screenshot](https://user-images.githubusercontent.com/49980364/185827840-46ca2ad2-ad52-43fd-a8d1-3abca3cf90af.png)

**Comment by ray1025** [comment]
> > @a31550277
> > 您好，我在synology上執行遇到問題，專案每週都會卡在
> > Start shopee coins bot v1.1.0.
> > Start to load cookies.
> > Cookies loaded.
> > Start to login shopee.
> > Try to login by username and password.
> > Login form submitted. Waiting for redirect.
> > Operation timeout exceeded.
> > 我已經試了兩週都要用電腦重新跑一次cookie再傳過去synology
> > 請問你也會這樣嗎???
> > 要如何解決???
> > 謝謝。
> 
> Hi, 請問是否有截圖？這可能是 bug。

請問我需要另開issues嗎？

**Comment by wdzeng** [comment]
> > > @a31550277
> > > 您好，我在synology上執行遇到問題，專案每週都會卡在
> > > Start shopee coins bot v1.1.0.
> > > Start to load cookies.
> > > Cookies loaded.
> > > Start to login shopee.
> > > Try to login by username and password.
> > > Login form submitted. Waiting for redirect.
> > > Operation timeout exceeded.
> > > 我已經試了兩週都要用電腦重新跑一次cookie再傳過去synology
> > > 請問你也會這樣嗎???
> > > 要如何解決???
> > > 謝謝。
> > 
> > Hi, 請問是否有截圖？這可能是 bug。
> 
> 請問我需要另開issues嗎？

好，麻煩你了。
