### ISSUE TITLE
bot-automation repository disabled

### ISSUE THREAD

**Issue by lyenliang** [wdzeng/shopee-coins-bot#24]
[bot-automation](https://github.com/wdzeng/bot-automation) 專案現在登入會看到 `Access to this repository has been disabled by GitHub Staff due to a violation of GitHub's terms of service` 訊息。請問有人知道是違反 github 哪條 [terms of service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service) 嗎？

**Comment by wdzeng** [comment]
GitHub Actions [不能拿來做跟 CI/CD 無關的事情](https://docs.github.com/en/site-policy/github-terms/github-terms-for-additional-products-and-features#actions)。

> if using GitHub-hosted runners, any other activity unrelated to the production, testing, deployment, or publication of the software project associated with the repository where GitHub Actions are used.

**Comment by lyenliang** [comment]
那請問原本 bot-automation 會把 cookie 存放在什麼地方呢？

我想在自己的 gitlab private repository 實現自動簽到的功能，但不知道 cookie 該存在哪邊比較好       @@

**Comment by wdzeng** [comment]
Hi,

是放在原 repo 內的 credential branch。但既然 repo 被 ban 了，cookie 大概撈不出來，而且還需要當初加密用的 AES key。

**Comment by lyenliang** [comment]
了解了，感謝你，我可能會把 cookie 放到 gitlab CI/CD variables 內 XD
