### ISSUE TITLE
Operation timeout exceeded.

### ISSUE THREAD

**Issue by ray1025** [wdzeng/shopee-coins-bot#28]
Status: Downloaded newer image for hyperbola/shopee-coins-bot:1
Start shopee coins bot v1.0.17.
Passing password from command line is considered insecure. Should use environment variable or password file.
Start to load cookies.
Failed to load cookies: EACCES: permission denied, open '/cookie'
Start to login shopee.
Try to login by username and password.
Login form submitted. Waiting for redirect.
Operation timeout exceeded.

試了好幾次，一直收不到簡訊。

我用其它電腦登入蝦皮時，在等簡訊頁面60秒後，再點選再次發送簡訊才馬上收到1封，是不是蝦皮故意的???

**Comment by ray1025** [comment]
Start to load cookies.
Cookies loaded.
Start to login shopee.
Already logged in.
Start to save cookie.
Cookie saved.
Coin already received.

我把B電腦用好的cookie直接複製到A電腦執行就好了...

**Comment by ray1025** [comment]
用帳號密碼登入的時候
docker run --rm -v /home/test/cookie:/cookie hyperbola/shopee-coins-bot:1 -c /cookie -u XXX -p XXX

用其它電腦複製過來的cookie登入時
docker run --rm -v /home/test/cookie:/cookie hyperbola/shopee-coins-bot:1 -c /cookie

**Comment by ray1025** [comment]
在A電腦想要截圖時
docker run --rm -v /home/test/cookie:/cookie hyperbola/shopee-coins-bot:1 -c /cookie -u XXX -p XXX -s /docker

**Comment by ray1025** [comment]
我左思右想應該是我A電腦的資料夾權限有問題吧

**Comment by wdzeng** [comment]
> 我左思右想應該是我A電腦的資料夾和cookie檔案權限有問題吧

不是。你遇到的問題跟 #21 一模一樣。因為重複的關係我先關掉這個 issue。

> 在A電腦想要截圖時 docker run --rm -v /home/test/cookie:/cookie hyperbola/shopee-coins-bot:1 -c /cookie -u XXX -p XXX -s /docker

我沒看懂 `-s /docker` 的意思。我只覺得這失敗很正常。

**Comment by ray1025** [comment]
-s /docker
我是想把截圖存在docker這個資料夾...

**Comment by wdzeng** [comment]
> `-s /docker`
> 我是想把截圖存在 docker 這個資料夾 ...

你確定 /docker 這個資料夾存在嗎？不存在的話就會 permission denied 喔。

**Comment by ray1025** [comment]
看來是我的失誤@@
