### ISSUE TITLE
新增對 arm/v7 架構的支援

### ISSUE THREAD

**Issue by 0penYour1egs** [wdzeng/shopee-coins-bot#29]
wdzeng 您好,

我嘗試在docker上安裝時得到反饋：

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
```

請問是否有機會製作 arm 架構下可用的 image 呢？

目前使用環境是 Raspberry Pi 4 Model B 8GB RAM。

**Comment by boneyhsu** [comment]
希望能有 ARM 可以使用的 image...
讓樹莓派也可以使用
感謝！

**Comment by wdzeng** [comment]
> 希望能有 ARM 可以使用的 image...
> 讓樹莓派也可以使用
> 感謝！

我會做，但我最近得了口國的病毒，痛得不得了。

**Comment by wdzeng** [comment]
我猜這可能跟 #25 是同一件事，我先關掉此串喔。

**Comment by wdzeng** [comment]
Hi @0penYour1egs @boneyhsu,

我已經在 #25 完成對 arm64 的支援了，並且有熱心鄉民協助測試。不過，我目前沒有做 arm/v7 的支援，如果需要的話，請再跟我說。

**Comment by 0penYour1egs** [comment]
> Hi @0penYour1egs @boneyhsu,
> 
> 我已經在 #25 完成對 arm64 的支援了，並且有熱心鄉民協助測試。不過，我目前沒有做 arm/v7 的支援，如果你們的樹梅派需要支援 arm/v7 的話，請再跟我說。

Hi @wdzeng  辛苦了！
是的！我需要arm/v7，有勞您了 ^^

docker: no matching manifest for linux/arm/v7 in the manifest list entries.

**Comment by wdzeng** [comment]
Hi @0penYour1egs,

請試試看 `hyperbola/shopee-coins-bot:truckski-1.1.1-alpha.1` 版本的 image。

**Comment by 0penYour1egs** [comment]
Hi @wdzeng 

我不確定問題所在，依然無法執行

image 下載=
docker pull ghcr.io/wdzeng/shopee-coins-bot:truckski-edge@sha256:6bfbd8c964fe334b3bbeffcc3575cbbda45dbc57b1235f0e5e631142e022aebf

指令= 
pi@raspberrypi:~ $ docker run -it -v /home/pi/cookie:/cookie hyperbola/shopee-coins-bot:truckski-edge -u xxx -p xxx -c /cookie

反饋如下=
exec /usr/bin/tini: exec format error

出現格式錯誤的問題，方便協助我判斷可能的問題點嗎？謝謝 ^^

**Comment by wdzeng** [comment]
> Hi @wdzeng
> 
> 我不確定問題所在，依然無法執行
> 
> image 下載= docker pull ghcr.io/wdzeng/shopee-coins-bot:truckski-edge@sha256:6bfbd8c964fe334b3bbeffcc3575cbbda45dbc57b1235f0e5e631142e022aebf
> 
> 指令= pi@raspberrypi:~ $ docker run -it -v /home/pi/cookie:/cookie hyperbola/shopee-coins-bot:truckski-edge -u xxx -p xxx -c /cookie
> 
> 反饋如下= exec /usr/bin/tini: exec format error
> 
> 出現格式錯誤的問題，方便協助我判斷可能的問題點嗎？謝謝 ^^

Hi @0penYour1egs,

是我把 dockerfile 寫爛了 = =

請再試試看 `hyperbola/shopee-coins-bot:truckski-1.1.1-alpha.2`。

**Comment by wdzeng** [comment]
Hi @0penYour1egs,

踩到 libseccomp 的雷了。方便知道你的 docker version 嗎？

**Comment by boneyhsu** [comment]
> Hi @boneyhsu,
> 
> 踩到 libseccomp 的雷了，這是作業系統很底層的問題，跟程式本身無關。重包 image 可能可以解決。
> 
> 方便知道你的 docker version 嗎？

@wdzeng  您好
我的 RPi 4 Docker 版本
Docker version 20.10.17, build 100c701

非常感謝...

**Comment by wdzeng** [comment]
Hi @boneyhsu,

方便詢問你的 rpi 裝的作業系統嗎？

**Comment by boneyhsu** [comment]
@wdzeng ，感謝您花時間找問題

執行下段指令，依然出現同樣的錯誤訊息 `Node.js[7]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.`
```
cd /tmp
wget http://ftp.debian.org/debian/pool/main/libs/libseccomp/seccomp_2.5.4-1+b1_armhf.deb
sudo dpkg -i seccomp_2.5.4-1+b1_armhf.deb
```

我 RPi4B 的 OS 版本資訊如下：

Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by wdzeng** [comment]
> @wdzeng ，感謝您花時間找問題
> 
> 執行下段指令，依然出現同樣的錯誤訊息 `Node.js[7]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.`
> ```
> cd /tmp
> wget http://ftp.debian.org/debian/pool/main/libs/libseccomp/seccomp_2.5.4-1+b1_armhf.deb
> sudo dpkg -i seccomp_2.5.4-1+b1_armhf.deb
> ```
> 
> 我 RPi4B 的 OS 版本資訊如下：
> 
> Distributor ID: Raspbian
> Description:    Raspbian GNU/Linux 10 (buster)
> Release:        10
> Codename:       buster

Hi @boneyhsu,

請問你在執行以下指令時，系統是否有顯示什麼訊息呢？想請你再執行一次一模一樣的指令，然後把訊息貼上來。

```
cd /tmp wget http://ftp.debian.org/debian/pool/main/libs/libseccomp/seccomp_2.5.4-1+b1_armhf.deb sudo dpkg -i seccomp_2.5.4-1+b1_armhf.deb
```

感恩感恩～

**Comment by boneyhsu** [comment]
@wdzeng 您好：

執行命令：
`pi@raspberrypi:~/shopee $ docker run -it -v /home/pi/shopee/my-cookie:/cookie hyperbola/shopee-coins-bot:truckski-1.1.1-alpha.2 -u username -p password , -c /cookie`

顯示訊息如下，沒有其他訊息：
**Node.js[7]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.** 

感謝花時間 debug
如還需要其他相關資訊，再麻煩提出喔
感恩！

**Comment by wdzeng** [comment]
Hi @boneyhsu,

不好意思我沒有講清楚，我是指執行 `cd` `wget` `sudo` 那三行指令的訊息。

**Comment by boneyhsu** [comment]
@wdzeng  您好：
執行結果沒有任何錯誤喔，截圖如下 （包含執行 docker 的錯誤訊息）
感謝！
![2022-08-11_10h36_32](https://user-images.githubusercontent.com/18432711/184055855-08929a24-4cdb-4db3-8bae-aa48c731862d.png)

**Comment by wdzeng** [comment]
> @wdzeng 您好： 執行結果沒有任何錯誤喔，截圖如下 （包含執行 docker 的錯誤訊息） 感謝！ ![2022-08-11_10h36_32](https://user-images.githubusercontent.com/18432711/184055855-08929a24-4cdb-4db3-8bae-aa48c731862d.png)

了解，看樣子只剩重包 image 這條路了....

**Comment by wdzeng** [comment]
@boneyhsu 不好意思這麼晚才回覆，這段期間實在沒什麼進展。

請再試試這個方法：

```bash
cd /tmp
wget http://ftp.debian.org/debian/pool/main/libs/libseccomp/libseccomp-dev_2.5.4-1+b1_armhf.deb
sudo dpkg -i libseccomp-dev_2.5.4-1+b1_armhf.deb
```

然後，再試一次執行機器人。感謝！

**Comment by wdzeng** [comment]
Close this issue due to inactivity.
