### ISSUE TITLE
GitHub Actions 無法運行

### ISSUE THREAD

**Issue by lin-ycv** [wdzeng/shopee-coins-bot#30]
版本1.1.0
Error 1
https://gist.github.com/lin-ycv/fef55c4fef9c6a2ca40493d04aad3035
版本1.0.17
Error 125
https://gist.github.com/lin-ycv/7b2ce0eddffd914b2b1201f8cbed9fd5

**Comment by lin-ycv** [comment]
執行的action:
https://gist.github.com/lin-ycv/b5eb98ff74cf97c934068dd07b94ae26

**Comment by wdzeng** [comment]
> 執行的action:
> https://gist.github.com/lin-ycv/b5eb98ff74cf97c934068dd07b94ae26

等等，怎麼還有人在用 actions。我以為那個 repo 被 ban 之後就沒人在用了，就把 action source 砍了 =_=

**Comment by lin-ycv** [comment]
好像是只fork與main被ban，但如果是自己開新的目前是還能用
可以的話希望開發者可以繼續支援actions謝謝

**Comment by wdzeng** [comment]
> 好像是只 fork 與 main 被 ban，但如果是自己開新的目前是還能用，一直到前天都還是正常運作
> 可以的話希望開發者可以繼續支援 actions 謝謝

你好，

Fork 是被 ban 了沒錯；但 main 沒有，是我主動移除的。因為 fork 沒了之後 main 留著也沒有意義。

目前我並未打算再把 Action source 放回 main，因為我不希望 main 也被 GitHub ban 掉。Action source 依然保留在 git history，有需要的話可以自行拿去使用。

如果你需要一個能夠獨立運作的 bot-automation，請再透過私下管道與我聯繫。
