### ISSUE TITLE
請問可以使用node.js執行嗎？

### ISSUE THREAD

**Issue by ray1025** [wdzeng/shopee-coins-bot#32]
因為舊筆電無法安裝docker，我想測試使用Node.js環境執行，請問可以嗎？

**Comment by wdzeng** [comment]
> 因為舊筆電無法安裝docker，我想測試使用Node.js環境執行，請問可以嗎？

可以。以 npm build 可以把 ts 轉為 js。瀏覽器 driver 的部分需要自己注意一下。

**Comment by ray1025** [comment]
我指令這樣下，正確嗎？
git clone https://github.com/wdzeng/shopee-coins-bot
cd shopee-coins-bot
npm install
npm run build
node dist/index.js -c *** -u *** -p ***

**Comment by ray1025** [comment]
我現在沒有執行成功，是缺Firefox瀏覽器的核心嗎？

**Comment by wdzeng** [comment]
> 我指令這樣下，正確嗎？
> 
> ```
> git clone https://github.com/wdzeng/shopee-coins-bot
> cd shopee-coins-bot
> npm install
> npm run build
> node dist/index.js -c *** -u *** -p ***
> ```

是。

**Comment by wdzeng** [comment]
> 我現在沒有執行成功，是缺 Firefox 瀏覽器的核心嗎？

請求排除錯誤時貼 Log 是基本常識。

**Comment by ray1025** [comment]
$ node dist/index.js -u 12345678 -p 12345678
Start shopee coins bot v1.1.0.
Passing password from command line is considered insecure. Should use environment variable or password file.

然後就沒了@@

**Comment by wdzeng** [comment]
> ```
> $ node dist/index.js -u 12345678 -p 12345678
> Start shopee coins bot v1.1.0.
> Passing password from command line is considered insecure. Should use environment variable or password file.
> ```
> 
> 然後就沒了@@

> 我現在沒有執行成功，是缺 Firefox 瀏覽器的核心嗎？

很可能是，但這個機器人用的是 chromium。

**Comment by ray1025** [comment]
收到，我試試安裝chromium核心。
感恩。
