### ISSUE TITLE
每天自動登入卡在每週一重新驗證帳號密碼畫面

### ISSUE THREAD

**Issue by ray1025** [wdzeng/shopee-coins-bot#35]
每天自動執行，但每週一都會卡在重新驗證帳號密碼。

平常自動執行的日誌：

```
Start shopee coins bot v1.1.0.
Start to load cookies.
Cookies loaded.
Start to login shopee.
Already logged in.
Start to save cookie.
Cookie saved.
Coin received.
```

每週一卡住的日誌：

```
Start shopee coins bot v1.1.0.
Start to load cookies.
Cookies loaded.
Start to login shopee.
Try to login by username and password.
Login form submitted. Waiting for redirect.
Operation timeout exceeded.
```

另為了截圖，把 cookie 刪除後，重新用帳號密碼執行，卡在登入畫面。

日誌：

```
Start shopee coins bot v1.1.0.
No cookies given. Will try to login using username and password.
Start to login shopee.
Try to login by username and password.
Login form submitted. Waiting for redirect.
A screenshot has been put at /sc/screenshot.png.
Operation timeout exceeded.
```

畫面：
![123](https://user-images.githubusercontent.com/49980364/186407107-df2a3c72-d62d-4e9e-ada9-098b46ecb381.png)

執行機種：
Synology DS918+ 版本: 7.1-42661 Update 4 (實體記憶體16GB)
Docker 套件版本: 20.10.3-1308

**Comment by wdzeng** [comment]
> 每天自動執行，但每週一都會卡在重新驗證帳號密碼。
> 
> 平常自動執行的日誌：
> 
> ```
> Start shopee coins bot v1.1.0.
> Start to load cookies.
> Cookies loaded.
> Start to login shopee.
> Already logged in.
> Start to save cookie.
> Cookie saved.
> Coin received.
> ```
> 
> 每週一卡住的日誌：
> 
> ```
> Start shopee coins bot v1.1.0.
> Start to load cookies.
> Cookies loaded.
> Start to login shopee.
> Try to login by username and password.
> Login form submitted. Waiting for redirect.
> Operation timeout exceeded.
> ```
> 
> 另為了截圖，把 cookie 刪除後，重新用帳號密碼執行，卡在登入畫面。
> 
> 日誌：
> 
> ```
> Start shopee coins bot v1.1.0.
> No cookies given. Will try to login using username and password.
> Start to login shopee.
> Try to login by username and password.
> Login form submitted. Waiting for redirect.
> A screenshot has been put at /sc/screenshot.png.
> Operation timeout exceeded.
> ```
> 
> 畫面： ![123](https://user-images.githubusercontent.com/49980364/186407107-df2a3c72-d62d-4e9e-ada9-098b46ecb381.png)
> 
> 執行機種： Synology DS918+ 版本: 7.1-42661 Update 4 (實體記憶體16GB) Docker 套件版本: 20.10.3-1308

Hi @ray1025,

我無法重現這個錯誤，我這邊登入無論有沒有 cookie 都完全沒問題。

這個錯誤只會在星期一發生嗎？這很詭異耶。

**Comment by ray1025** [comment]
@wdzeng 
您好：
1.我用電腦反覆測試的結論，蝦皮網頁登入，蝦皮每週一的00:00之後都會要重新驗證一次帳號密碼，但如果有cookie就不用簡訊認證。
2.截圖有確實自動填入帳號密碼，只剩機器人沒按登入鍵。
3.設備網路無斷線紀錄，且反覆測試過，應該不是網路問題。

**Comment by mouson** [comment]
我在自己的主機(AlmaLinux 8)上也發生了同樣的狀況。動作同樣卡在 `Login form submitted. Waiting for redirect.` 而後 timeout。查看 screenshot 同樣是卡在登入頁已輸入帳號密碼。

請問我還可以做些什麼動作協助解決這問題呢？

**Comment by wdzeng** [comment]
> 我在自己的主機(AlmaLinux 8)上也發生了同樣的狀況。動作同樣卡在 `Login form submitted. Waiting for redirect.` 而後 timeout。查看 screenshot 同樣是卡在登入頁已輸入帳號密碼。
> 
> 請問我還可以做些什麼動作協助解決這問題呢？
> 

完蛋，我這邊一直沒辦法重現，也不知道怎麼修。

**Comment by lin-ycv** [comment]
最近比較常看到著個問題
```
Start shopee coins bot v1.1.0.
Start to load cookies.
Cookies loaded.
Start to login shopee.
Try to login by username and password.
Login form submitted. Waiting for redirect.
Login failed: please login via SMS.
SMS authentication is required.
Error: Process completed with exit code 2.
```
之前再執行一次就OK (不知道為甚麼)
但今天執行n次都卡在這，也不會收到簡訊

**Comment by ray1025** [comment]
> 最近比較常看到著個問題
> 
> ```
> Start shopee coins bot v1.1.0.
> Start to load cookies.
> Cookies loaded.
> Start to login shopee.
> Try to login by username and password.
> Login form submitted. Waiting for redirect.
> Login failed: please login via SMS.
> SMS authentication is required.
> Error: Process completed with exit code 2.
> ```
> 
> 之前再執行一次就OK (不知道為甚麼) 但今天執行n次都卡在這，也不會收到簡訊

你試試看參數不要加-x或--no-sms，另外加-f參數。

**Comment by wdzeng** [comment]
@lin-ycv 我覺得是你的 cookie 失效了，可能你改過密碼之類的。只要重新登一次就可以了。
沒收到簡訊的原因，我猜是因為你下了 `--no-sms`。

**Comment by wdzeng** [comment]
說到這個 @ray1025 大大，你遇到這個問題還在嗎？如果還在的話是否方便提供你下的 docker 指令？

**Comment by mouson** [comment]
停了幾天排程，看到這串手動執行了一下排程。目前看到以下訊息：

![image](https://user-images.githubusercontent.com/858588/191641803-7bf71e21-afee-4caa-a366-41c4e0739607.png)

但並沒有收到簡訊，我猜目前卡在跟使用者索取簡訊驗證的畫面。

---

以下是我目前執行的 shell script 內容。

```
docker run \
        -v $HOME_PATH/cookie:/cookie \
        -v $HOME_PATH/PASSWORD:/PASSWORD \
        -v $HOME_PATH/screen1:/screenshot \
        hyperbola/shopee-coins-bot:1 -f \
        -u myaccount@email.com -P /PASSWORD \
        -c /cookie \
        -s /screenshot
```

**Comment by wdzeng** [comment]
> 停了幾天排程，看到這串手動執行了一下排程。目前看到以下訊息：
> 
> ![image](https://user-images.githubusercontent.com/858588/191641803-7bf71e21-afee-4caa-a366-41c4e0739607.png)
> 
> 但並沒有收到簡訊，我猜目前卡在跟使用者索取簡訊驗證的畫面。
> 
> ---
> 
> 以下是我目前執行的 shell script 內容。
> 
> ```
> docker run \
>         -v $HOME_PATH/cookie:/cookie \
>         -v $HOME_PATH/PASSWORD:/PASSWORD \
>         -v $HOME_PATH/screen1:/screenshot \
>         hyperbola/shopee-coins-bot:1 -f \
>         -u myaccount@email.com -P /PASSWORD \
>         -c /cookie \
>         -s /screenshot
> ```

Hi @mouson,

到這裡表示簡訊確實有寄出去了。

**Comment by ray1025** [comment]
> 說到這個 @ray1025 大大，你遇到這個問題還在嗎？如果還在的話是否方便提供你下的 docker 指令？

@wdzeng 大神您好，我是用synology的[docker套件](https://www.synology.com/zh-tw/dsm/feature/docker)，他只能設定環境變數和附加檔案或資料夾，沒辦法而外增加參數的指令。

稍早我那個回答，移除--no-sms，增加-f，是我在GitHub Actions測試上發現的，已自行解決。

**Comment by ray1025** [comment]
我現在已經放棄在synology上執行了，我先關閉此問題了，謝謝。
