### ISSUE TITLE
【許願】請問是否新增推播到 Telegram 的功能

### ISSUE THREAD

**Issue by NeiL978** [wdzeng/shopee-coins-bot#36]
你好 請問能許願新增推播到Telegram的功能嗎？
如果可以就太完美了 謝謝🙏

**Comment by wdzeng** [comment]
Hi,

目前沒有。簽到功能跟推播是兩件獨立的事情，不適合喇在一個 repo 裡面。額外寫一個 repo 是可以考慮的。

如果你想要，請在標題加上`【許願】`，人數夠多我就會做。

**Comment by LostSunset** [comment]
附議+1
