### ISSUE TITLE
Unexpected end of JSON input 這問題是？

### ISSUE THREAD

**Issue by kai456789** [wdzeng/shopee-coins-bot#38]
指令如下，也在 cookie 用 `touch` 建立 coin 檔案 。

```
docker run -it -v ~/cookie/coin:/cookie hyperbola/shopee-coins-bot:1 -u '' -p '' -c /cookie
```

會出現 `Unexpected end of JSON input`

```
Start shopee coins bot v1.1.0.
Start to load cookies.
Failed to load cookies: Unexpected end of JSON input
Start to login shopee.
Failed to login. Missing username or password.
```

用的是甲骨文的 ARM。

**Comment by wdzeng** [comment]
> 指令如下，也在 cookie 用 `touch` 建立 coin 檔案 。
> 
> ```
> docker run -it -v ~/cookie/coin:/cookie hyperbola/shopee-coins-bot:1 -u '' -p '' -c /cookie
> ```
> 
> 會出現 `Unexpected end of JSON input`
> 
> ```
> Start shopee coins bot v1.1.0.
> Start to load cookies.
> Failed to load cookies: Unexpected end of JSON input
> Start to login shopee.
> Failed to login. Missing username or password.
> ```
> 
> 用的是甲骨文的 ARM。

抱歉，我覺得有些文不對題。標題寫出現了 `Unexpected end of JSON input` 的錯誤訊息，內文給的錯誤訊息卻是 `Failed to login. Missing username or password.`。

是否可以再麻煩你釐清，感謝！

**Comment by wdzeng** [comment]
好，我看懂了。

你的 cookie 格式是爛掉了，因為那是一個空檔案。然而，你給的帳號密碼都是空字串，這當然登不進去。

**Comment by kai456789** [comment]
已成功用上 感謝 
在ubuntu上 沒用-u的話 cookie寫不進去
