### ISSUE TITLE
機器人在部分機器上 Operation timeout

### ISSUE THREAD

**Issue by mcc1** [wdzeng/shopee-coins-bot#40]
這幾天開始好像無法運作了?
用 docker 的 latest 跟 kelly 都會卡在 redirection
Output 如下

```
Start shopee coins bot v1.1.0.
Passing password from command line is considered insecure. Should use environment variable or password file.
Start to load cookies.
Cookies loaded.
Start to login shopee.
Try to login by username and password.
Login form submitted. Waiting for redirect.
Operation timeout exceeded.
```

**Comment by mcc1** [comment]
奇怪 我今天測試又可以了 可是我前三天都失敗 - -

**Comment by Rex1152** [comment]
一樣的問題
卡在帳密輸入完畢後沒按登入
帳號有輸入只是碼掉了
![screenshot](https://user-images.githubusercontent.com/78677857/196328199-b15c2c79-389e-4ae5-a020-11ad2ec354ac.png)

**Comment by wdzeng** [comment]
> 奇怪 我今天測試又可以了 可是我前三天都失敗 - - 我會再注意看看

有人回報過同樣的問題 (#35)，因此很可能是 bot 本身有 bug。但因為我重現不了，因此一直沒辦法修。

**Comment by Rex1152** [comment]
這問題應該只有在synology上會發作
一陣子就會遇到連續好幾天不work過幾天又好了
同時在synology與ubuntu跑就只有synology會這樣

**Comment by wdzeng** [comment]
> 這問題應該只有在synology上會發生
> 一陣子就會遇到連續好幾天不work過幾天又好了
> 同時在synology與ubuntu跑就只有synology會這樣
> 把docker砍掉重建也沒用

好慘，之前回報的也是在 NIS。我沒有那台機器，大概幫不上忙了。

**Comment by tasict** [comment]
我觀察了一下，發現這個發生的時機蠻有趣的，登入無法redirect時，都是在cookie內的幾個"expiry"欄位到期，沒辦法Renew的關係，而且看起來是每個平台都會發生．我的作法是發生時，手動把每個expiry過期日隨便往後改一點，讓他重新跑一遍就又可以正常了．
舉例來說 
"expiry":1669080790 -> "expiry":1679080790 (2022/11/21 -> 2023/03/18)

參考看看吧

**Comment by wdzeng** [comment]
> 我觀察了一下，發現這個發生的時機蠻有趣的，登入無法redirect時，都是在cookie內的幾個"expiry"欄位到期，沒辦法Renew的關係，而且看起來是每個平台都會發生．我的作法是發生時，手動把每個expiry過期日隨便往後改一點，讓他重新跑一遍就又可以正常了．
> 舉例來說 
> "expiry":1669080790 -> "expiry":1679080790 (2022/11/21 -> 2023/03/18)
> 
> 參考看看吧
>       
> 

感謝 我再實驗看看 OAO

**Comment by workfunction** [comment]
我也遇到一樣的問題，照 @tasict 的方式改 cookie 沒辦法解決。
Cookie 整份清空一樣會卡在 `Login form submitted. Waiting for redirect.`
截圖是卡在登入畫面，帳號密碼都填好了。

**Comment by jrchen982** [comment]
我這邊也時常會卡住，實測過容易卡住的設備為 [Acute Angle AA – B4 Mini PC](https://osslab.tv/shop/aa/acute_angle_mini_pc/)，與 [AWS EC2 t3a.small](https://instances.vantage.sh/aws/ec2/t3a.small)，全部 OS version 皆為 Ubuntu 22.04。
如果發生 `Operation timeout exceeded.`，我都把卡住的 cookie 丟到 Intel Core i7 或 i9 的 Ubuntu VM 重跑一次，通常就馬上簽到成功。
根據其他人反映 synology 也會這樣，我認為要重現這個問題，在低階一點的 CPU 上較容易實現，頻率蠻高的，平均每 4~7 天就出現一次。
我在想會不會是 selenium 在低階 CPU 上，讓登入網頁長出來的時間，晚於登入表單被 trigger 的時間 (?

**Comment by ray1025** [comment]
已經連續兩次了，都是卡在這畫面。
![screenshot](https://user-images.githubusercontent.com/49980364/232183224-b513cfcf-4439-4b75-9009-8879cda7bb43.png)



Start shopee coins bot v1.2.0.
Start to load cookies.
Start to login shopee.
Try to login by username and password.
Login form submitted. Waiting for redirect.
Login failed: please login via SMS.
An SMS message is sent to your mobile. Once you click the link I will keep going. I will wait for you and please complete it in 10 minutes.
Login permitted.
Start to save cookie.
Cookie saved.
A screenshot has been put at /screenshot/screenshot.png.
Operation timeout exceeded.

**Comment by jrchen982** [comment]
> 今日連續發生3次，都是卡在這畫面。 ![screenshot](https://user-images.githubusercontent.com/49980364/232183224-b513cfcf-4439-4b75-9009-8879cda7bb43.png)
> 
> 第1次，用cookie： Start shopee coins bot v1.2.0. Start to load cookies. Cookies loaded. Start to login shopee. Already logged in. Start to save cookie. Cookie saved. A screenshot has been put at /screenshot/screenshot.png. Operation timeout exceeded. Error: 操作逾時。 Error: Process completed with exit code 4.
> 
> 第2、3次，改用帳密： Start shopee coins bot v1.2.0. Start to load cookies. Failed to load cookies: ENOENT: no such file or directory, open '/repo/plain_credential' Start to login shopee. Try to login by username and password. Login form submitted. Waiting for redirect. Login failed: please login via SMS. An SMS message is sent to your mobile. Once you click the link I will keep going. I will wait for you and please complete it in 10 minutes. Login permitted. Start to save cookie. Cookie saved. A screenshot has been put at /screenshot/screenshot.png. Operation timeout exceeded. Error: 操作逾時。 Error: Process completed with exit code 4.

@ray1025 我狀況跟你一樣耶，換主機跑也都失敗。

我在猜是不是因為簽到 button 上顯示的名字換了，現在顯示 `完成簽到，即可獲得 XX 蝦幣！`，如果有簽過，會顯示 `明天再回來簽到，可獲得 XX 蝦幣！`，根據 @wdzeng 大神的[原始碼](https://github.com/wdzeng/shopee-coins-bot/blob/main/src/text.ts)來看，好像原本顯示的文字應該是 `今日簽到獲得`，而如果已經簽到過，原本應該會顯示 `明天再回來領取`。

不曉得是不是這樣導致 bot 抓不到按鈕而操作逾時。

**Comment by wdzeng** [comment]
收到，馬上處理。另外建議另開新 issue。

**Comment by wdzeng** [comment]
> 今日連續發生3次，都是卡在這畫面。 ![screenshot](https://user-images.githubusercontent.com/49980364/232183224-b513cfcf-4439-4b75-9009-8879cda7bb43.png)
> 
> 第1次，用cookie： Start shopee coins bot v1.2.0. Start to load cookies. Cookies loaded. Start to login shopee. Already logged in. Start to save cookie. Cookie saved. A screenshot has been put at /screenshot/screenshot.png. Operation timeout exceeded. Error: 操作逾時。 Error: Process completed with exit code 4.
> 
> 第2、3次，改用帳密： Start shopee coins bot v1.2.0. Start to load cookies. Failed to load cookies: ENOENT: no such file or directory, open '/repo/plain_credential' Start to login shopee. Try to login by username and password. Login form submitted. Waiting for redirect. Login failed: please login via SMS. An SMS message is sent to your mobile. Once you click the link I will keep going. I will wait for you and please complete it in 10 minutes. Login permitted. Start to save cookie. Cookie saved. A screenshot has been put at /screenshot/screenshot.png. Operation timeout exceeded. Error: 操作逾時。 Error: Process completed with exit code 4.

感謝回報，移動到 #51。此 issue 留給 @mcc1 處理部分設備無法簽到的問題。

**Comment by wdzeng** [comment]
Hi all,

抱歉這個問題閒置這麼久依然沒有進展，因為我這裡並沒有合適的機器可以進行測試。

我計畫在之後的版本改用 Pupeteer，希望屆時能解決這個問題。

**Comment by wdzeng** [comment]
不再處理 v1 的 issue。移至 [v2](https://github.com/wdzeng/shopee-coins-bot/tree/features/v2)。
