### ISSUE TITLE
這周開始無法使用 Login failed: need email Auth

### ISSUE THREAD

**Issue by anlo1220** [wdzeng/shopee-coins-bot#42]
沒收到驗證簡訊或者郵件

> docker run -it -v "/root/shopee:/secret" hyperbola/shopee-coins-bot:1 -c /secret/shopee-cookie -u xxxxxx -p xxxxx -s /root/shopee -f
> Start shopee coins bot v1.0.17.
> Passing password from command line is considered insecure. Should use environment variable or password file.
> Start to load cookies.
> Cookies loaded.
> Start to login shopee.
> Try to login by username and password.
> Login form submitted. Waiting for redirect.
> Login failed: need email Auth
> Failed to save screenshot: EACCES: permission denied, open '/root/shopee/screenshot.png'

**Comment by wdzeng** [comment]
< v1.2.0 是不支援信箱驗證的，請用最新版本。
