### ISSUE TITLE
蝦皮官網頁面更新而無法簽到

### ISSUE THREAD

**Issue by wdzeng** [wdzeng/shopee-coins-bot#51]
04/15 [網友反映無法簽到](https://github.com/wdzeng/shopee-coins-bot/issues/40#issuecomment-1509499900)。

@ray1025 @jrchen982

**Comment by ray1025** [comment]
謝謝大神^^

**Comment by jrchen982** [comment]
謝謝大神^^

**Comment by wdzeng** [comment]
已於 v1.2.1 修復，請再試試看。

**Comment by ray1025** [comment]
我今天已經先手動點過，剛剛測試v1.2.1版，可以偵測，應該沒問題了。感恩^^

Start shopee coins bot v1.2.1.
Start to load cookies.
Cookies loaded.
Start to login shopee.
Already logged in.
Start to save cookie.
Cookie saved.
Coin already received.
A screenshot has been put at /screenshot/screenshot.png.

**Comment by jrchen982** [comment]
我這邊也測試成功，確定沒問題了，感謝大神👍👍👍
```console
Start shopee coins bot v1.2.1.
Start to load cookies.
Cookies loaded.
Start to login shopee.
Already logged in.
Start to save cookie.
Cookie saved.
Coin received.
```
