### ISSUE TITLE
蝦皮簽到成功，但實際上沒有領到蝦幣

### ISSUE THREAD

**Issue by ray1025** [wdzeng/shopee-coins-bot#53]
最近bot都有成功，但是蝦幣都無法領到，在不同天時有嘗試過切換IP也沒用，研判蝦皮有加入裝置的認證機制，一個裝置一天可能只領一次。docker打包檔的裝置資訊有辦法設定隨機嗎？

**Comment by wdzeng** [comment]
我會再確認👀👀

**Comment by anlo1220** [comment]
同樣問題
會顯示明天領取0.1但是紀錄都沒 不同IP&不同天測試都依樣 
隔天手動可以按簽到
![image](https://i.imgur.com/jU5RgQi.jpg)

**Comment by danielhuang-030** [comment]
+1
手動簽到沒問題，但透過機器人簽到後就會強制回溯到第一天
當天沒有取得蝦幣也無法再點擊，隔天就正常了

**Comment by ray1025** [comment]
我是4/24以前都正常，4/25開始遇到這問題，4/26~4/30換過IP還是沒用，中間5/1有暫停bot，手動點正常，5/2用bot又GG...

**Comment by ray1025** [comment]
今天用bot還是GG...

**Comment by wdzeng** [comment]
我晚上修。

可以請各位詳細描述遇到的狀況嗎？我目前的理解是：

即使先前已經連續簽到多天，只要一使用 bot，簽到就不會成功。並且隔天開始又會從第一天開始計數。

這樣的描述正確嗎？

**Comment by ray1025** [comment]
不是唷。是bot有正常成功執行，蝦皮無獲得紀錄。

**Comment by ray1025** [comment]
我個人研判蝦皮網頁簽到，會讀取裝置資訊。同個裝置資訊，一天只會給一次蝦幣。

**Comment by hijacker000** [comment]
我也遇到同樣問題
所以這幾天，我乾脆自己用python+playwright寫程式自動簽到
前幾天簽到都可以，但今天簽到竟然也發生同樣的問題
我是在我自己電腦上執行的，所以應該不是ip的問題

**Comment by Supoyuan** [comment]
應該是蝦皮加了什麼東西防止機器人自動簽到吧 
要抓手機封包才知道了

**Comment by wdzeng** [comment]
> 應該是蝦皮加了什麼東西防止機器人自動簽到吧 要抓手機封包才知道了

是，我懷疑這才是原因

**Comment by ray1025** [comment]
![1111](https://user-images.githubusercontent.com/49980364/236613832-2dfcd263-9dbe-465a-90f7-ba441b2d5eba.jpg)

**Comment by ray1025** [comment]
限制相同裝置...

**Comment by wdzeng** [comment]
> 限制相同裝置...



> ![1111](https://user-images.githubusercontent.com/49980364/236613832-2dfcd263-9dbe-465a-90f7-ba441b2d5eba.jpg)

這個資訊很實用喔，感謝！

**Comment by danielhuang-030** [comment]
> 限制相同裝置...

感覺客服不是很清楚情況，以我的使用情境 docker 是在位於日本的 VM 上執行，也只有一組帳號；所以應該是「多個裝置登入同一組帳號」，根本跟回覆的內容完全相反。不過能夠確定的是，蝦皮那邊確實做了某種反制機器人的手段～機器人能運行將近半年也算是難得，感謝 @wdzeng 的工具囉～

**Comment by hijacker000** [comment]
我是在猜他是不是能偵測chrome的headless模式

**Comment by wdzeng** [comment]
> 我是在猜他是不是能偵測chrome的headless模式

不太可能吧

**Comment by wdzeng** [comment]
這個週末太忙了沒辦法修，請各位再等幾天，不好意思了

**Comment by wdzeng** [comment]
確認能夠重現。因為只有一支帳號沒辦法做太多試驗，看看明天能不能修好。

**Comment by wdzeng** [comment]
> 我是在猜他是不是能偵測chrome的headless模式

打臉我自己。這個很可能就是問題來源。

**Comment by hijacker000** [comment]
> > > 我是在猜他是不是能偵測chrome的headless模式
> 
> > 不太可能吧
> 
> 打臉我自己。這個很可能就是問題來源，我猜 shopee 最近有摻驗 headless 的設定。

我是用playwright，firefox的headless模式目前是可以用

**Comment by a6428775** [comment]
> > > 我在猜他不是能測 chrome 的無頭模型
> 
> > 不太可能吧
> 
> 打臉我自己。這個很可能就是問題來源，我猜shopee最近有試驗headless的設置。

去除webdriver特征，好像就可以了。
options = Options()
options.add_argument("--disable-blink-features")
options.add_argument("--disable-blink-features=AutomationControlled")

**Comment by wdzeng** [comment]
> > > > 我在猜他不是能測 chrome 的無頭模型
> > 
> > 
> > > 不太可能吧
> > 
> > 
> > 打臉我自己。這個很可能就是問題來源，我猜shopee最近有試驗headless的設置。
> 
> 去除webdriver特征，好像就可以了。 options = Options() options.add_argument("--disable-blink-features") options.add_argument("--disable-blink-features=AutomationControlled")

行不通 QaQ

**Comment by a6428775** [comment]
> 所有者

咦!!
我是直接用python + selenium 但沒有使用無頭模式，
但原本也是簽到後會成功簽到，但無法獲得蝦幣。
我去除webdriver特性後，簽到成功後就順利獲得蝦幣了。
給您參考~~

**Comment by 000hen** [comment]
> > > > > 我在猜他不是能測 chrome 的無頭模型
> > > 
> > > 
> > > > 不太可能吧
> > > 
> > > 
> > > 打臉我自己。這個很可能就是問題來源，我猜shopee最近有試驗headless的設置。
> > 
> > 去除webdriver特征，好像就可以了。 options = Options() options.add_argument("--disable-blink-features") options.add_argument("--disable-blink-features=AutomationControlled")
> 
> 行不通 QaQ
> 

要不要試試看在頁面載入之前把`navigator.webdriver`封鎖

**Comment by EugeneBrave** [comment]
> > > > > > 我在猜他不是能測 chrome 的無頭模型
> > > > 
> > > > 
> > > > > 不太可能吧
> > > > 
> > > > 
> > > > 打臉我自己。這個很可能就是問題來源，我猜shopee最近有試驗headless的設置。
> > > 
> > > 
> > > 去除webdriver特征，好像就可以了。 options = Options() options.add_argument("--disable-blink-features") options.add_argument("--disable-blink-features=AutomationControlled")
> > 
> > 
> > 行不通 QaQ
> 
> 要不要試試看在頁面載入之前把`navigator.webdriver`封鎖
確實，我在driver.get之前去執行execute_cdp_cmd，把navigator.webdriver消除掉後，看起來就能正常收幣了。

driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
  "source": """
    Object.defineProperty(navigator, 'webdriver', {
      get: () => undefined
    })
  """
})
driver.get(urlLogin)

**Comment by wdzeng** [comment]
> > > > > > > 我在猜他不是能測 chrome 的無頭模型
> > > > > 
> > > > > 
> > > > > > 不太可能吧
> > > > > 
> > > > > 
> > > > > 打臉我自己。這個很可能就是問題來源，我猜shopee最近有試驗headless的設置。
> > > > 
> > > > 
> > > > 去除webdriver特征，好像就可以了。 options = Options() options.add_argument("--disable-blink-features") options.add_argument("--disable-blink-features=AutomationControlled")
> > > 
> > > 
> > > 行不通 QaQ
> > 
> > 
> > 要不要試試看在頁面載入之前把`navigator.webdriver`封鎖
> 
> 確實，我用python在driver.get之前去執行execute_cdp_cmd，把navigator.webdriver消除掉後，看起來就能正常收幣了。
> 
> ```
> driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
>   "source": """
>     Object.defineProperty(navigator, 'webdriver', {
>       get: () => undefined
>     })
>   """
> })
> driver.get(urlLogin)
> ```

我用的語言是 NoseJS，但找不到對應的寫法 orz

**Comment by EugeneBrave** [comment]
> > > > > > > > 我在猜他不是能測 chrome 的無頭模型
> > > > > > 
> > > > > > 
> > > > > > > 不太可能吧
> > > > > > 
> > > > > > 
> > > > > > 打臉我自己。這個很可能就是問題來源，我猜shopee最近有試驗headless的設置。
> > > > > 
> > > > > 
> > > > > 去除webdriver特征，好像就可以了。 options = Options() options.add_argument("--disable-blink-features") options.add_argument("--disable-blink-features=AutomationControlled")
> > > > 
> > > > 
> > > > 行不通 QaQ
> > > 
> > > 
> > > 要不要試試看在頁面載入之前把`navigator.webdriver`封鎖
> > 
> > 
> > 確實，我用python在driver.get之前去執行execute_cdp_cmd，把navigator.webdriver消除掉後，看起來就能正常收幣了。
> > ```
> > driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
> >   "source": """
> >     Object.defineProperty(navigator, 'webdriver', {
> >       get: () => undefined
> >     })
> >   """
> > })
> > driver.get(urlLogin)
> > ```
> 
> 我用的語言是 NodeJS，但找不到對應的寫法 orz

我有查到nodejs可以用sendDevToolsCommand來達成，但這是2021年的做法，不知道現在行不行得通?
```
  const command_result = await driver.sendDevToolsCommand(
    "Page.addScriptToEvaluateOnNewDocument",
    {
      source: `
        Object.defineProperty(navigator, 'webdriver', {
          get: () => undefined
        })
      `,
    }
  );
  console.log(command_result);
```
from: [https://github.com/SeleniumHQ/selenium/issues/8636](https://github.com/SeleniumHQ/selenium/issues/8636)

**Comment by wdzeng** [comment]
> > > > > > > > > 我在猜他不是能測 chrome 的無頭模型
> > > > > > > 
> > > > > > > 
> > > > > > > > 不太可能吧
> > > > > > > 
> > > > > > > 
> > > > > > > 打臉我自己。這個很可能就是問題來源，我猜shopee最近有試驗headless的設置。
> > > > > > 
> > > > > > 
> > > > > > 去除webdriver特征，好像就可以了。 options = Options() options.add_argument("--disable-blink-features") options.add_argument("--disable-blink-features=AutomationControlled")
> > > > > 
> > > > > 
> > > > > 行不通 QaQ
> > > > 
> > > > 
> > > > 要不要試試看在頁面載入之前把`navigator.webdriver`封鎖
> > > 
> > > 
> > > 確實，我用python在driver.get之前去執行execute_cdp_cmd，把navigator.webdriver消除掉後，看起來就能正常收幣了。
> > > ```
> > > driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
> > >   "source": """
> > >     Object.defineProperty(navigator, 'webdriver', {
> > >       get: () => undefined
> > >     })
> > >   """
> > > })
> > > driver.get(urlLogin)
> > > ```
> > 
> > 
> > 我用的語言是 NodeJS，但找不到對應的寫法 orz
> 
> 我有查到nodejs可以用sendDevToolsCommand來達成，但這是2021年的做法，不知道現在行不行得通?
> 
> ```
>   const command_result = await driver.sendDevToolsCommand(
>     "Page.addScriptToEvaluateOnNewDocument",
>     {
>       source: `
>         Object.defineProperty(navigator, 'webdriver', {
>           get: () => undefined
>         })
>       `,
>     }
>   );
>   console.log(command_result);
> ```
> 
> from: [SeleniumHQ/selenium#8636](https://github.com/SeleniumHQ/selenium/issues/8636)

神仙解藥

**Comment by wdzeng** [comment]
請試試看 v1.3.0，也感謝各位的幫忙！

**Comment by ray1025** [comment]
v1.3.0測試正常，感謝各位大神。

**Comment by anlo1220** [comment]
同樣v1.3.0測試正常 感謝
