### ISSUE TITLE
【許願】Armhf/arm32 bit支援

### ISSUE THREAD

**Issue by yoni13** [wdzeng/shopee-coins-bot#63]
`docker: no matching manifest for linux/arm/v7 in the manifest list entries.`

希望能在舊版的 32 bit arm上跑。

[Pre complied chrome driver](https://stackoverflow.com/a/57586200)

**Comment by wdzeng** [comment]
之前有嘗試過，不過因為做完沒辦法測試，就下架了。這次做完之後再麻煩你測試囉。

**Comment by wdzeng** [comment]
Hi @yoni13, 請試試看 `docker.io/hyperbola/shopee-coins-bot:1.3.1-alpha.0`。

**Comment by yoni13** [comment]
yoni@orangepipcplus:~$ ./shopee.sh
Start shopee coins bot v1.3.1-alpha.0.
Start to load cookies.
Cookies loaded.
Start to login shopee.
Already logged in.
Start to save cookie.
Cookie saved.
Coin already received.
成功

**Comment by wdzeng** [comment]
感恩🥹

等發布正式 release 就關掉這個 issue。
