### ISSUE TITLE
登入逾時，沒收到簡訊或信件通知

### ISSUE THREAD

**Issue by 94ione** [wdzeng/shopee-coins-bot#64]
```sh
[root@test ~]# docker run -v /www/shopee/coin:/cookie hyperbola/shopee-coins-bot:1 -u username-p password-c /cookie
Start shopee coins bot v1.3.1.
Passing password from command line is considered insecure. Should use environment variable or password file.
Option `--pass` is deprecated and will be removed in the future.
Start to load cookies.
Failed to load cookies: Unexpected end of JSON input
Start to login shopee.
Try to login by username and password.
Login form submitted. Waiting for redirect.
Operation timeout exceeded.
```

**Comment by wdzeng** [comment]
我想先確定的是，

```
docker run -v /www/shopee/coin:/cookie hyperbola/shopee-coins-bot:1 -u username-p password-c /cookie
                                                                               ^^         ^^
```

你有加空格嗎？

**Comment by 94ione** [comment]
謝謝版主如此迅速的回應，我在執行時，有先遇到Failed to load cookies: EISDIR: illegal operation on a directory, read的問題，看一下本板內ISSUE的解決方式(https://github.com/wdzeng/shopee-coins-bot/issues/17)，創建後有解決了，所以.....我的coin這裡是個檔案，不是目錄耶，因止此照您說的要進行截圖，會出現Failed to save screenshot: ENOENT: no such file or directory, open '/www/shopee/coin/screenshot.png'。謝謝!

**Comment by 94ione** [comment]
我截到圖了，是卡在他出現身份驗證，"為保護您的帳戶安全,請選擇以下其中一種方式驗證"，因為沒有按，所以就沒有繼續，那該如何使用強制使用簡訊或MAIL驗證呢。謝謝!

**Comment by wdzeng** [comment]
Hi, 請問是否方便提供截圖？我在測試時的情況是只會遇到手機或 email 其中之一的驗證，同時遇到兩者是第一次，所以機器人無法處理這種情況。

**Comment by wdzeng** [comment]
另，`Failed to load cookies: Unexpected end of JSON input` 是正常的，不用理會。

**Comment by 94ione** [comment]
![image](https://github.com/wdzeng/shopee-coins-bot/assets/95640892/de73ae85-06fb-4df0-84c5-d1d7906507a5)

**Comment by 94ione** [comment]
我試著在電腦上登入後，用這個方式: https://github.com/wdzeng/pinkoi-coins-bot/blob/main/docs/cookie_instruction.md，將上面的COOKIE，複製貼上至創建的那個coin檔，出現Failed to load cookies: Unexpected token _ in JSON at position 0，是否不能這樣做，還是有哪又是我這忽略的了呢，謝謝

**Comment by wdzeng** [comment]
> 我試著在電腦上登入後，用這個方式: [https://github.com/wdzeng/pinkoi-coins-bot/blob/main/docs/cookie_instruction.md，將上面的COOKIE，複製貼上至創建的那個coin檔，出現Failed](https://github.com/wdzeng/pinkoi-coins-bot/blob/main/docs/cookie_instruction.md%EF%BC%8C%E5%B0%87%E4%B8%8A%E9%9D%A2%E7%9A%84COOKIE%EF%BC%8C%E8%A4%87%E8%A3%BD%E8%B2%BC%E4%B8%8A%E8%87%B3%E5%89%B5%E5%BB%BA%E7%9A%84%E9%82%A3%E5%80%8Bcoin%E6%AA%94%EF%BC%8C%E5%87%BA%E7%8F%BEFailed) to load cookies: Unexpected token _ in JSON at position 0，是否不能這樣做，還是有哪又是我這忽略的了呢，謝謝

Hi, 那篇文是寫給 [pinkoi-coins-bot](https:/github.com/wdzeng/pinkoi-coins-bot) 的。這兩個 bot 背後的原理不同，不能用同樣的方式處理 cookie。

**Comment by wdzeng** [comment]
OK 看樣子蝦皮登入的流程變了。我修。

**Comment by 94ione** [comment]
辛苦您了。謝謝！

**Comment by wdzeng** [comment]
Hi @94ione,

我已經更新機器人的登入邏輯了。有一個不好的消息是，蝦皮最近把登入的步驟調嚴了，你可能會因為遇到拼圖遊戲被擋下來。如果是這樣的話，你可以能要想辦法透過調整環境來繞過拼圖遊戲（例如你跑 docker 的機器的 IP 本來就登入過），否則機器人目前是沒辦法使用的。

如果你沒辦法繞過拼圖遊戲，我近期會再調整 cookie 的處理方式，讓蝦皮的機器人可以像 [pinkoi-coins-bot](https://github.com/wdzeng/pinkoi-coins-bot) 一樣可以人為設定。到時候就可以繞過拼圖遊戲。

**Comment by 94ione** [comment]
您好，您真是專業的，果然出現拼圖卡住了，我來想想如何試著用該IP來首登試試。謝謝您!!

**Comment by wdzeng** [comment]
那我先關掉這個。如果怎麼試都繞不過拼圖的話，請再打開。

**Comment by 94ione** [comment]
經過一晚研究，終於在遠端可以先登錄，但回到機器人要登還是卡住了圖片這關，看來殘念啊，還是謝謝版主的更新！

**Comment by 94ione** [comment]
回報版主，今日找了其他三個帳號來試，都用 1.3.2 版的，都一樣卡在拼圖這關，所以 .... 期待版大下一版看有沒有機會突破喔，再次謝謝您的辛苦開發 !! 辛苦了 !!

**Comment by wdzeng** [comment]
@94ione 也許你會想試試看 [v2](https://github.com/wdzeng/shopee-coins-bot/tree/features/v2)。

**Comment by 94ione** [comment]
版神.....您有沒有休息呀，太感動了。不過這v2我測試了，已不會有相關錯誤訊息，不過一樣測了三個帳號，無論有沒有簽過，最後回傳的訊息都是已簽到過，但實際卻沒有簽到領取，驗證一下是有正常登入的，因為下balance是有幣的，想再抓個圖看狀況如何，但此版好像不支援截圖了。還是那句，謝謝您辛苦的開發!!

**Comment by wdzeng** [comment]
> 版神.....您有沒有休息呀，太感動了。不過這v2我測試了，已不會有相關錯誤訊息，不過一樣測了三個帳號，無論有沒有簽過，最後回傳的訊息都是已簽到過，但實際卻沒有簽到領取，驗證一下是有正常登入的，因為下balance是有幣的，想再抓個圖看狀況如何，但此版好像不支援截圖了。還是那句，謝謝您辛苦的開發!!

我覺得應該是你都餵到同一個 cookie，所以簽到的都是同一個帳號。

**Comment by 94ione** [comment]
版主一直有在FOLLOW耶，真的很感動，當時是想測試有簽到跟還沒簽的狀況訊息是否一樣，但我目前都先驗證一個帳號，使用tag :edge / 2.0.0-alpha.1 / 2 都一樣會顯示已簽到，但實際是沒有的，回到無論手機、電腦要再簽一次，就會出現報錯，請明天再試。我想可能您還在修改中，因此就沒有一直回報反應，期待9月...... ^^

**Comment by wdzeng** [comment]
> 版主一直有在FOLLOW耶，真的很感動，當時是想測試有簽到跟還沒簽的狀況訊息是否一樣，但我目前都先驗證一個帳號，使用tag :edge / 2.0.0-alpha.1 / 2 都一樣會顯示已簽到，但實際是沒有的，回到無論手機、電腦要再簽一次，就會出現報錯，請明天再試。我想可能您還在修改中，因此就沒有一直回報反應，期待9月...... ^^

這真是太詭異了 .... 這很像五月時蝦皮因為偵測瀏覽器自動化的反應 ....

**Comment by 94ione** [comment]
![image](https://github.com/wdzeng/shopee-coins-bot/assets/95640892/e3227a78-9b59-44c1-bdae-47ee6fd6eef5)
就像這樣，若用機器人進行後，就會出現這狀況訊息，進行了就需隔天用手機或網頁才能簽
