### ISSUE TITLE
[v2] Checkin 時出現錯誤訊息 Missing required cookie: shopee_webUnique_ccd

### ISSUE THREAD

**Issue by wdzeng** [wdzeng/shopee-coins-bot#68]
我用whoami正常，但是用checkin也是出現這個錯誤
Invalid cookie.
Missing required cookie: shopee_webUnique_ccd

ps.
1.我的 cookie 來自一般的 Chrome 瀏覽器
2.我的登入方式是帳號密碼登入

_Originally posted by @ray1025 in https://github.com/wdzeng/shopee-coins-bot/issues/65#issuecomment-1748056300_

**Comment by wdzeng** [comment]
Hi @ray1025 你的狀況跟其他人不同，我移動到這裡來。

想請你幫忙試試看用「無痕」的 Chrome 取得 cookie。感謝！

**Comment by wdzeng** [comment]
cc @94ione

**Comment by ray1025** [comment]
已經重新測試了，使用無痕的 Chrome 瀏覽器，帳號密碼登入取得的cookie。
whoami、balance、history指令都正常。
checkin指令出現"You are not logged in. Is your cookie expired?"錯誤。

**Comment by wdzeng** [comment]
了解。那剩餘的問題留給 #66 解決。我先關掉這個。
